#!/bin/bash
cd $OPENSHIFT_REPO_DIR
sed -i 's/@OPENSHIFT_DIY_IP@/'"$OPENSHIFT_DIY_IP"'/g' server/config.openshift.yml
sed -i 's/@OPENSHIFT_DIY_PORT@/'"$OPENSHIFT_DIY_PORT"'/g' server/config.openshift.yml
sed -i 's/@OPENSHIFT_POSTGRESQL_DB_HOST@/'"$OPENSHIFT_POSTGRESQL_DB_HOST"'/g' server/config.openshift.yml
sed -i 's/@OPENSHIFT_POSTGRESQL_DB_PORT@/'"$OPENSHIFT_POSTGRESQL_DB_PORT"'/g' server/config.openshift.yml
