template: Hello, %s!

defaultName: ${DW_DEFAULT_NAME:-Stranger}

# Database settings.
database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver
  # the username
  user: sa
  # the password
  password: sa
  # the JDBC URL
  url: jdbc:h2:./target/example
  properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hbm2ddl.auto: create

server:
  type: simple
  applicationContextPath: /api
  adminContextPath: /admin
  connector:
    type: http
    port: @OPENSHIFT_DIY_PORT@
    bindHost: @OPENSHIFT_DIY_IP@

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: DEBUG

    org.hibernate.SQL: ALL

  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB