environment: DEV

database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:./target/example
  properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hbm2ddl.auto: create
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  rootPath: /api/*
  connector:
    type: http
    port: 8080
  requestLog:
      appenders: []

logging:
  level: INFO
  loggers:
    com.example.app: DEBUG
    org.hibernate.SQL: ALL
  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB