environment: OPENSHIFT
database:
  driverClass: org.postgresql.Driver
  user: adminfrjkfs1
  password: BV2MdwpFBSu4
  url: jdbc:postgresql://@OPENSHIFT_POSTGRESQL_DB_HOST@:@OPENSHIFT_POSTGRESQL_DB_PORT@/fomo
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: create-drop
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  rootPath: /api/*
  connector:
    type: http
    port: @OPENSHIFT_DIY_PORT@
    bindHost: @OPENSHIFT_DIY_IP@
  requestLog:
      appenders: []

logging:
  level: INFO
  loggers:
    org.hibernate.engine.internal: WARN
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB
