defaultName: ${DW_DEFAULT_NAME:-Stranger}
# Database settings.
database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:./target/example
# For when we connect it up with Postgres
#      Root User: adminfrjkfs1
#      Root Password: BV2MdwpFBSu4
#      Database Name: fomo
#
#   Connection URL: postgresql://$OPENSHIFT_POSTGRESQL_DB_HOST:$OPENSHIFT_POSTGRESQL_DB_PORT
  properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hbm2ddl.auto: create
server:
  type: simple
  applicationContextPath: /api
  adminContextPath: /admin
  connector:
    type: http
    port: @OPENSHIFT_DIY_PORT@
    bindHost: @OPENSHIFT_DIY_IP@
  requestLog:
      appenders: []

logging:
  level: INFO
  loggers:
    com.example.app: DEBUG
    org.hibernate.SQL: ALL
  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB